### ISSUE TITLE
Additional modules required 

### ISSUE THREAD

**Issue by robmoore** [datamill-co/singer-runner#2]
I followed the instructions in the readme to install from this repo but had to install these modules as well:

- click
- dataclasses

After doing so I was able to run `singer-runner` successfully.

**Comment by robmoore** [comment]
Work in progress in https://github.com/datamill-co/singer-runner/pull/3.

**Comment by awm33** [comment]
Resolved by https://github.com/datamill-co/singer-runner/pull/3
